---
# Create startup system services scripts for apereo-cas

- name: Create systemd control unit for standalone Apereo CAS service
  when: apereo_cas_container == 'standalone' and ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7
  template:
    src: cas.unit.j2
    dest: "/etc/systemd/system/{{ apereo_cas_service }}.service"
    owner: root
    group: root
    mode: 0755
  notify: reload systemd

- name: Create sysvinit control script for standalone Apereo CAS service
  when: apereo_cas_container == 'standalone' and ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6
  template:
    src: cas.sysvinit.j2
    dest: "/etc/init.d/{{ apereo_cas_service }}"
    owner: root
    group: root
    mode: 0755

- name: Start standalone Apereo CAS service
  when: apereo_cas_container == 'standalone'
  service:
    name: "{{ apereo_cas_service }}"
    state: started
    enabled: yes

